[tasks.clean]
workspace = false
command = "cargo"
args = ["clean"]

[tasks.release]
workspace = false
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.mkdir-dist]
workspace = false
command = "docker"
args = ["cp ", "--volume", "${PWD}:/root/src", "--workdir", "/root/src", "joseluisq/rust-linux-darwin-builder:1.43.0", "cargo", "build", "--release", "--target", "x86_64-apple-darwin"]
dependencies = ["clean"]

[tasks.release-darwin]
workspace = false
command = "docker"
args = ["run", "--rm", "--volume", "${PWD}:/root/src", "--workdir", "/root/src", "joseluisq/rust-linux-darwin-builder:1.43.0", "cargo", "build", "-p", "async_msp_cli", "--release", "--target", "x86_64-apple-darwin"]
dependencies = ["clean"]

[tasks.release-windows]
workspace = false
command = "cross"
args = ["build", "--target", "x86_64-pc-windows-gnu", "--release"]
dependencies = ["clean"]

[tasks.release-arm]
workspace = false
command = "cross"
args = ["build", "-p", "async_msp_cli", "--target", "arm-unknown-linux-musleabihf", "--release"]
dependencies = ["clean"]

[tasks.release-armv7]
workspace = false
command = "cross"
args = ["build", "-p", "async_msp_cli", "--target", "armv7-unknown-linux-musleabihf", "--release"]
dependencies = ["clean"]

[tasks.dist-folder]
workspace = false
command = "mkdir"
args = ["-p", "dist"]

[tasks.copy-to-dist]
workspace = false
script = [
    "cp target/x86_64-pc-windows-gnu/release/async_msp_cli.exe dist/async_msp_cli_windows.exe",
    "cp target/x86_64-apple-darwin/release/async_msp_cli dist/async_msp_cli_darwin",
    "cp target/release/async_msp_cli dist/async_msp_cli_linux",
]
dependencies = ["dist-folder"]

[tasks.release-int32]
workspace = false
command = "cargo"
args = ["build", "--release", "--features", "suppport_int32_setting_type"]
dependencies = ["clean"]

[tasks.release-darwin-int32]
workspace = false
command = "docker"
args = ["run", "--rm", "--volume", "${PWD}:/root/src", "--workdir", "/root/src", "joseluisq/rust-linux-darwin-builder:1.43.0", "cargo", "build", "-p", "async_msp_cli",  "--target", "x86_64-apple-darwin", "--release", "--features", "suppport_int32_setting_type"]
dependencies = ["clean"]

[tasks.release-windows-int32]
workspace = false
command = "cross"
args = ["build", "-p", "async_msp_cli", "--target", "x86_64-pc-windows-gnu", "--release", "--features", "suppport_int32_setting_type"]
dependencies = ["clean"]

[tasks.release-arm-int32]
workspace = false
command = "cross"
args = ["build", "-p", "async_msp_cli", "--target", "arm-unknown-linux-musleabihf", "--release", "--features", "suppport_int32_setting_type"]
dependencies = ["clean"]

[tasks.release-armv7-int32]
workspace = false
command = "cross"
args = ["build", "-p", "async_msp_cli", "--target", "armv7-unknown-linux-musleabihf", "--release", "--features", "suppport_int32_setting_type"]
dependencies = ["clean"]

[tasks.copy-to-dist-int32]
workspace = false
script = [
    "cp target/x86_64-pc-windows-gnu/release/async_msp_cli.exe dist/async_msp_cli_windows_int32.exe",
    "cp target/x86_64-apple-darwin/release/async_msp_cli dist/async_msp_cli_darwin_int32",
    "cp target/release/async_msp_cli dist/async_msp_cli_linux_int32",
]
dependencies = ["dist-folder"]

[tasks.release-all]
workspace = false
dependencies = [
    "release",
    "release-darwin",
    "release-windows",
    "copy-to-dist",
]

[tasks.release-all-int32]
workspace = false
dependencies = [
    "release-int32",
    "release-darwin-int32",
    "release-windows-int32",
    "copy-to-dist-int32",
]
